package com.velasco.car;

import com.google.gson.Gson;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.*;


@Controller // This means that this class is a Controller
@RequestMapping(path="/cars") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CarRepository carRepository;

    @PostMapping
    public ResponseEntity createCar(@RequestBody Car car) throws URISyntaxException {
        Car sc = carRepository.save(car);
        return ResponseEntity.created(new URI("/clients/" + sc.getId())).body(sc);
    }

    @PutMapping("/{id}")
    public ResponseEntity updateClient(@PathVariable Integer id, @RequestBody Car car) {
        Car currentCar = carRepository.findById(id).orElseThrow(RuntimeException::new);
        currentCar.setMake(car.getMake());
        currentCar.setBody(car.getBody());
        currentCar.setModel(car.getModel());
        currentCar.setTransmission(car.getTransmission());
        currentCar = carRepository.save(car);

        return ResponseEntity.ok(currentCar);
    }

    @GetMapping
    public @ResponseBody Iterable<Car> getAllCars() {
        // This returns a JSON or XML with the users
        return carRepository.findAll();
    }

    @GetMapping(path="/{id}") // Map ONLY POST Requests
    public @ResponseBody Optional<Car> getCar (@PathVariable Integer id) {
        return carRepository.findById(id);
    }

    @DeleteMapping(path="/{id}") // Map ONLY POST Requests
    public @ResponseBody String delete (@PathVariable Integer id) {

        String response;
        try {
            carRepository.deleteById(id);
            response = "Deleted";
        } catch (Exception e) {
            response = "Error " + e.getMessage();
        }
        return response;
    }
}
